/* A few support routines that are meant to be linked to the object files
 * generated by the compiler. Just so we can do a little I/O for testing before
 * we get to the real integration work with the host OS. */

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>

uint64_t add64(uint64_t x, uint64_t y)
{
        return x + y;
}

uint64_t sub64(uint64_t x, uint64_t y)
{
        return x - y;
}

uint64_t mul64(uint64_t x, uint64_t y)
{
        return x * y;
}

uint64_t div64(uint64_t x, uint64_t y)
{
        return x / y;
}

uint64_t gt64(uint64_t x, uint64_t y)
{
        return x > y;
}

uint64_t lt64(uint64_t x, uint64_t y)
{
        return x < y;
}

uint64_t ge64(uint64_t x, uint64_t y)
{
        return x >= y;
}

uint64_t le64(uint64_t x, uint64_t y)
{
        return x <= y;
}

uint64_t eq64(uint64_t x, uint64_t y)
{
        return x == y;
}

uint64_t ne64(uint64_t x, uint64_t y)
{
        return x != y;
}

uint64_t print64(uint64_t x)
{
        printf("%" PRId64 "\n", x);
        return 0;
}

uint64_t prints(const char *s)
{
        fputs(s, stdout);
        return 0;
}
