/* A few support routines that are meant to be linked to the object files
 * generated by the compiler. Just so we can do a little I/O for testing before
 * we get to the real integration work with the host OS. */

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>

uint64_t print64(uint64_t x)
{
        printf("%" PRId64 "\n", x);
        return 0;
}

uint64_t prints(const char *s)
{
        fputs(s, stdout);
        return 0;
}

/* XXX wrong signature as long as we don't implement the x64 ABI (float
 * arguments!) */
uint64_t print_float(uint32_t inp)
{
        union {
                uint32_t i;
                float f;
        } x;
        x.i = inp;
        printf("%f\n", x.f);
        return 0;
}

/*
 * stdin, stdout, stderr are evil complicated macros on MSVC
 */

FILE *get_stdin(void)
{
        return stdin;
}

FILE *get_stdout(void)
{
        return stdout;
}

FILE *get_stderr(void)
{
        return stderr;
}


/* XXX: only to work around our unfinished type system */
int chartoint(char c) { return c; }
char inttochar(int c) { return (char) c; }
