/* A few support routines that are meant to be linked to the object files
 * generated by the compiler. Just so we can do a little I/O for testing before
 * we get to the real integration work with the host OS. */

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>

uint64_t print64(uint64_t x, uint64_t y)
{
        uint64_t r = x + y;
        printf("%" PRId64 "\n", r);
        return r;
}
